version = 1

[[annotations]]
path = ["apps/**", "packages/**", "tools/**", "schemas/**", "tests/**"]
SPDX-FileCopyrightText = "2026 Nolann Morencé et contributeurs"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "data/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Nolann Morencé et contributeurs"
SPDX-License-Identifier = "CC-BY-4.0"